import { Component, ElementRef, HostListener, OnInit, ViewChild } from '@angular/core';
import { MDMondServiceDS } from '../../_services/ds/MDMondServiceDS'


@Component({
  selector: 'app-creditorCertificate-designer',
  templateUrl: './creditorCertificate.component.html',
  styleUrls: ['./creditorCertificate.component.css']
})

export class creditorCertificateComponent implements OnInit {
  public creditorCertificateList: any;
  public fileIdentifier: string = "";
  public clientName: string = "";
  public certificateNumber: string = "";
  public CEDGreaterThan: string = "";
  public CEDLessThan: string = "";
  public clientLocationNumber: string = "";
  public firstName: string = "";
  public lastName: string = "";
  public clientCertificateNo: string = "";
  public additionalSearchValue: string = "";
  public additionalSearchField: string = "";
  public creditorListCount: string;
  public numberOfRecordsToFetch: string = "50"
  public rowsfound: string;
  selectedTab: number = 0;
  certificateDetails: any;
  auditHistoryDetails: any;
  premiumHistory: any;
  public param: {};
  public isShowCertificateDetail: boolean = false;
  public isSpinnerShow: boolean = false;

  @ViewChild('logicalDeleteFlag') logicalDeleteFlag: ElementRef;
  constructor(private mdMondServiceDS: MDMondServiceDS) { }


  ngOnInit() {
    this.rowsfound = '0 rows found';
    this.certificateDetails = "";
    this.premiumHistory = "";
    this.isShowCertificateDetail = true;
  }

  onClickOfCreditorCertificate() {
    // debugger;  
    let creditorListCountFormVariables = {
      fileIdentifier: this.fileIdentifier,
      clientName: this.clientName,
      certificateNumber: this.certificateNumber,
      certificateEffectiveDateMax: this.CEDGreaterThan,
      certificateEffectiveDateMin: this.CEDLessThan,
      internalLocationNumber: this.clientLocationNumber,
      applicantFirstName: this.firstName,
      applicantLastName: this.lastName,
      clientCertificateNumber: this.clientCertificateNo,
      additionalSearchValue: this.additionalSearchValue,
      additionalSearchField: this.additionalSearchField,
      "": ""
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchCertificateTotalCount', JSON.stringify(creditorListCountFormVariables), null).subscribe(
      data => {
        this.creditorListCount = JSON.parse(atob(data.value)).certificateTotalCount;
        this.getCreditorList();
      }, error => {
        debugger;
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJjZXJ0aWZpY2F0ZVRvdGFsQ291bnQiOiI4MCJ9" };
        // this.creditorListCount = JSON.parse(atob(data.value)).certificateTotalCount;
        // this.getCreditorList();
      });
  }

  getCreditorList() {
    this.isSpinnerShow = true;
    let formVariable = {
      fileIdentifier: this.fileIdentifier,
      clientName: this.clientName,
      certificateNumber: this.certificateNumber,
      certificateEffectiveDateMax: this.CEDGreaterThan,
      certificateEffectiveDateMin: this.CEDLessThan,
      internalLocationNumber: this.clientLocationNumber,
      applicantFirstName: this.firstName,
      applicantLastName: this.lastName,
      clientCertificateNumber: this.clientCertificateNo,
      additionalSearchValue: this.additionalSearchValue,
      additionalSearchField: this.additionalSearchField,
      "": this.creditorListCount,
      startRow: 0,
      numberOfRecordsToFetch: this.numberOfRecordsToFetch
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchCertificateList', JSON.stringify(formVariable), null).subscribe(
      data => {
        let creditorGridData = JSON.parse(atob(data.value)).certificateList_certificateSummary;
        for (var i = 0; i < creditorGridData.length; i++) {
          creditorGridData[i]['No'] = i;
          if (creditorGridData[i].logicalDeleteFlag == 'N') {
            creditorGridData[i].logicalDeleteFlag = false;
          } else {
            creditorGridData[i].logicalDeleteFlag = true;
          }

          if (creditorGridData[i].processedWithErrors == 'N') {
            creditorGridData[i].processedWithErrors = false;
          } else {
            creditorGridData[i].processedWithErrors = true;
          }
          if (creditorGridData[i].processedWithWarningFlag == 'N') {
            creditorGridData[i].processedWithWarningFlag = false;
          } else {
            creditorGridData[i].processedWithWarningFlag = true;
          }
        }

        this.creditorCertificateList = creditorGridData;
        this.rowsfound = this.creditorListCount + ' rows found' + '( ' + this.creditorCertificateList.length + ' rows fetched )';
        this.isSpinnerShow = false;
      }, error => {
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJjZXJ0aWZpY2F0ZUxpc3RfY2VydGlmaWNhdGVTdW1tYXJ5IjpbeyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzEzLCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImFwcGxpY2FudE5hbWUiOiJDaHd3d3RpYW4gRGVzYmllbnMiLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNTk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk3IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiTiIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn0seyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzE0LCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImNvYXBwbGljYW50TmFtZSI6IkJyd0RFUklDIExBUVVJTiIsImFwcGxpY2FudE5hbWUiOiJGUndERVJJQyBQQVFVSU4iLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNjk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk4IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiWSIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn0seyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzE0LCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImNvYXBwbGljYW50TmFtZSI6IkJyd0RFUklDIExBUVVJTiIsImFwcGxpY2FudE5hbWUiOiJGUndERVJJQyBQQVFVSU4iLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNjk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk4IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiWSIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn1dfQ==" };
        // let creditorGridData = JSON.parse(atob(data.value)).certificateList_certificateSummary;
        // for (var i = 0; i < creditorGridData.length; i++) {
        //   creditorGridData[i]['No'] = i;
        //   if (creditorGridData[i].logicalDeleteFlag == 'N') {
        //     creditorGridData[i].logicalDeleteFlag = false;
        //   } else {
        //     creditorGridData[i].logicalDeleteFlag = true;
        //   }

        //   if (creditorGridData[i].processedWithErrors == 'N') {
        //     creditorGridData[i].processedWithErrors = false;
        //   } else {
        //     creditorGridData[i].processedWithErrors = true;
        //   }
        //   if (creditorGridData[i].processedWithWarningFlag == 'N') {
        //     creditorGridData[i].processedWithWarningFlag = false;
        //   } else {
        //     creditorGridData[i].processedWithWarningFlag = true;
        //   }
        // }

        // this.creditorCertificateList = creditorGridData;
        // this.rowsfound = this.creditorListCount + ' rows found' + '( ' + this.creditorCertificateList.length + ' rows fetched )';
        // this.isSpinnerShow = false;
      });

  }

  onClickOfCreditorRow(event) {
    this.isShowCertificateDetail = false;
    this.param = {
      certificateIdentifier: event.data.certificateIdentifier,
      logicalDeleteFlag: event.data.logicalDeleteFlag
    }

    this.selectedTab = 1;
    let certificateFormvariables = {
      fileHeaderId: event.data.fileHeaderIdentifier,
      certificateId: event.data.certificateIdentifier
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchCertificateDetails', JSON.stringify(certificateFormvariables), null).subscribe(
      data => {
        this.certificateDetails = JSON.parse(atob(data.value));
        this.fetchPremiumHistory(event);
        this.fetchTransactionAuditHistory(event);
      }, error => {
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJjZXJ0aWZpY2F0ZURhdGEiOiJ7XCJjZXJ0aWZpY2F0ZUhpc3RvcnlcIjogW3tcImNlcnRpZmljYXRlTnVtYmVyXCI6IFwiQ0kwMDAwMDAwMDA3NjUwMFwiLCBcInVuaXF1ZUNlcnRpZmljYXRlTnVtYmVyXCI6IFwiMjEzNjU1MFwiLCBcImZpbGVOYW1lXCI6IFwiRXh0cmFjdCAyMDE4MDMwMSB0byAyMDIwMDUzMSAzX0Rldl8yMTM2NTUwLnhsc3hcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiA5MTc2LCBcImZpbGVMb2FkRGF0ZVRpbWVcIjogXCIyMDE5LTAzLTA3VDA0OjU4OjAwLjAwMFpcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJOZXcgQnVzaW5lc3NcIn1dfSIsImNyZWRpdG9yRGF0YUpzb24iOiJ7XCJmaWxlSW5mb1wiOiB7XCJwYXJ0bmVyTmFtZVwiOiBcIkxHTVwiLCBcIm51bWJlck9mUmVjb3Jkc1wiOiAzLCBcImZpbGVDcmVhdGVkRGF0ZVwiOiBcIjIwMjAtMDYtMDRUMDA6MDA6MDAuMDAwWlwiLCBcImZpbGVMb2FkRGF0ZVwiOiBcIjIwMjEtMDUtMDdUMDM6NTQ6MzYuMDAwWlwiLCBcInByb2Nlc3NlZFdpdGhFcnJvckZsYWdcIjogXCJOXCIsIFwicGFydG5lcklkZW50aWZpZXJcIjogXCI4NTI3NTc3OVwiLCBcImZpbGVJZGVudGlmaWVyXCI6IFwiMDAwMDA5NTBcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJQb2xpY3kgRmVlZFwiLCBcInByb2R1Y3RUeXBlXCI6IFwiU1BcIiwgXCJwcm9kdWN0SWRcIjogNSwgXCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWdcIjogXCJOXCJ9LCBcImNlcnRpZmljYXRlXCI6IHtcImNlcnRpZmljYXRlUHJvY2Vzc2VkV2l0aEVycm9yRmxhZ1wiOiBcIk5cIiwgXCJjZXJ0aWZpY2F0ZUxvZ2ljYWxEZWxldGVGbGFnXCI6IFwiTlwiLCBcImNlcnRpZmljYXRlUGxhblByb2R1Y3RJbmZvSWRlbnRpZmllclwiOiBcIjExN1wiLCBcInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllclwiOiBcIjIxMzY1NTBcIiwgXCJjZXJ0aWZpY2F0ZU51bWJlclwiOiBcIkNJMDAwMDAwMDAwNzY1MDBcIiwgXCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGVcIjogXCIyMDE5LTAzLTA3VDAwOjAwOjAwLjAwMFpcIiwgXCJjZXJ0aWZpY2F0ZVRlcm1EYXRlXCI6IFwiOTk5OS0xMi0zMVQwMDowMDowMC4wMDBaXCIsIFwiY2VydGlmaWNhdGVQcm9kdWN0VHlwZVwiOiBcIlNQXCIsIFwiaW50ZXJuYWxMb2NhdGlvbk51bWJlclwiOiBcIjg1MDg0MDU0XCIsIFwiY2VydGlmaWNhdGVTdGF0dXNSZWFzb25cIjogXCJUQkRcIiwgXCJjZXJ0aWZpY2F0ZVN0YXR1c1wiOiBcIkFjdGl2ZVwiLCBcImNlcnRpZmljYXRlU3ViU3RhdHVzXCI6IFwiQWN0aXZlXCIsIFwicGxhblByb2R1Y3RJbmZvSWRcIjogMTE3LCBcInBsYW5OYW1lXCI6IFwiU2luZ2xlIFByZW1pdW0gLSBFc3NlbnRpYWwgUGx1cyBcIiwgXCJwbGFuTnVtYmVyXCI6IFwiMDU1NzZcIiwgXCJwbGFuRGVzY3JpcHRpb25cIjogXCJFc3NlbnRpYWwgUGx1cyAzME5SIChST0MgTG93KSBcIiwgXCJwcm9kdWN0SWRcIjogNSwgXCJsb2FuXCI6IHtcIkxvYW5BY2NvdW50TnVtYmVyXCI6IFwiMDAwMFwiLCBcIkFubnVhbGl6ZWRJbnRlcmVzdFJhdGVcIjogMS4wNywgXCJQZXJpb2RpY1BheW1lbnRBbW91bnRcIjogMjYzLjQ0LCBcIkxvYW5UeXBlXCI6IFwiMVwiLCBcIkxvYW5QYXltZW50RnJlcXVlbmN5XCI6IFwiMjZcIiwgXCJMb2FuVHlwZUNhdGVnb3J5XCI6IFwiMFwiLCBcIkxvYW5BbW91bnRcIjogNDc5MDguMzgsIFwiTG9hbkFtb3J0aXphdGlvblwiOiAwLCBcIkxvYW5Qcm9jZXNzZWRXaXRoRXJyb3JGbGFnXCI6IFwiTlwiLCBcIkxvYW5Mb2dpY2FsRGVsZXRlRmxhZ1wiOiBcIk5cIiwgXCJMb2FuTGFzdFVwZGF0ZWREYXRlXCI6IFwiMjAyMS0wNS0wN1QwMzo1NDozOC4wMDBaXCIsIFwiTG9hblN1YlR5cGVcIjogXCIwMVwiLCBcIkxvYW5BbXRXaXRob3V0SW5zdXJhbmNlTG9jXCI6IDQ2MzEzLjM4LCBcIkxvYW5PdXRzdGFuZGluZ0JhbGFuY2VcIjogMC4wLCBcIkxvYW5PcmlnaW5hbExvYWREYXRlXCI6IFwiMjAyMS0wNS0wN1QwMzo1NDozOC4wMDBaXCIsIFwiTG9hblRlcm1cIjogODQsIFwiTG9hbkVmZmVjdGl2ZURhdGVcIjogXCIyMDE5LTAzLTA3VDAwOjAwOjAwLjAwMFpcIiwgXCJMb2FuUmVzaWR1YWxWYWx1ZUFtb3VudFwiOiAwLjAsIFwiSW5zdXJlZExvYW5MZWFzZUFtb3VudFwiOiA0NzkwOC4zOCwgXCJEZWFsVHlwZVwiOiBcIkZcIn0sIFwiYXBwbGljYW50XCI6IFt7XCJhcHBsaWNhbnRTZXF1ZW5jZU51bWJlclwiOiAxLCBcImFwcGxpY2FudEZpcnN0TmFtZVwiOiBcIkJsYWluZVwiLCBcImFwcGxpY2FudExhc3ROYW1lXCI6IFwiRGVudG9uXCIsIFwiYXBwbGljYW50RGF0ZU9mQmlydGhcIjogXCIxOTY1LTA2LTAyVDAwOjAwOjAwLjAwMFpcIiwgXCJhcHBsaWNhbnRQaG9uZTFcIjogXCI1MDY2NDAxMzQyXCIsIFwiZ2VuZGVyXCI6IFwiTVwiLCBcImlzU21va2VyXCI6IFwiVVwiLCBcImNvcnJlc3BvbmRlbmNlTGFuZ3VhZ2VcIjogXCJFXCIsIFwiY29ycmVwb25kZW5jZVR5cGVcIjogXCJFXCIsIFwiYXBwbGljYW50UHJvY2Vzc2VkV2l0aEVycm9yRmxhZ1wiOiBcIk5cIiwgXCJhcHBsaWNhbnRMb2dpY2FsRGVsZXRlRmxhZ1wiOiBcIk5cIiwgXCJpbnRlcm5hbEFwcGxpY2FudElkZW50aWZpZXJcIjogXCIyMDAwODMwNzlcIiwgXCJpbnN1cmVkRmxhZ1wiOiBcIllcIiwgXCJhcHBsaWNhbnRQcm92aW5jZVwiOiBcIk5CXCIsIFwiY29tbXVuaWNhdGlvbkNvbnNlbnRGbGFnXCI6IFwiTlwiLCBcInRheEV4ZW1wdEZsYWdcIjogXCJOXCIsIFwiYXBwbGljYW50QWRkcmVzc1wiOiBbe1wiYWRkcmVzc1R5cGVcIjogXCJNQUlMSU5HXCIsIFwiYWRkcmVzc0xpbmUxXCI6IFwiOCBFQk9OWSBMQU5FXCIsIFwiY2l0eVwiOiBcIlFVSVNQQU1TSVNcIiwgXCJwcm92aW5jZVwiOiBcIk5CXCIsIFwicG9zdGFsQ29kZVwiOiBcIkUyRzFUOFwiLCBcImNvdW50cnlcIjogXCJDQVwiLCBcImFkZHJlc3NMb2dpY2FsRGVsZXRlRmxhZ1wiOiBcIk5cIn1dLCBcImFwcGxpY2FudENvdmVyYWdlXCI6IFt7XCJjb3ZlcmFnZVNlcXVlbmNlTnVtYmVyXCI6IDEsIFwiY292ZXJhZ2VBbW91bnRcIjogNTk2LjAsIFwiY292ZXJhZ2VQcmVtaXVtQW1vdW50XCI6IDQ3OC41LCBcImNvdmVyYWdlUHJlbWl1bVRheFwiOiAwLjAsIFwiY292ZXJhZ2VSZXNpZHVhbEFtb3VudFwiOiAwLjAsIFwiY292ZXJhZ2V0UmVzaWR1YWxQcmVtaXVtQW1vdW50XCI6IDAuMCwgXCJjb3ZlcmFnZVJlc2lkdWFsUHJlbWl1bVRheFwiOiAwLjAsIFwiY292ZXJhZ2VFZmZlY3RpdmVEYXRlXCI6IFwiMjAxOS0wMy0wN1QwMDowMDowMC4wMDBaXCIsIFwiY292ZXJhZ2VUZXJtXCI6IDg0LjAsIFwiY292ZXJhZ2VFeHBpcnlEYXRlXCI6IFwiMjAyNi0wMy0wN1QwMDowMDowMC4wMDBaXCIsIFwiY292ZXJhZ2VFbGltaW5hdGlvblBlcmlvZFR5cGVcIjogXCIzME5SXCIsIFwiY292ZXJhZ2VQcm9jZXNzZWRXaXRoRXJyb3JGbGFnXCI6IFwiTlwiLCBcImNvdmVyYWdlTG9naWNhbERlbGV0ZUZsYWdcIjogXCJOXCIsIFwiY292ZXJhZ2VDb2RlXCI6IFwiRElcIiwgXCJjb3ZlcmFnZUlkZW50aWZpZXJcIjogXCIyXCIsIFwiYXBwbGljYW50Q292ZXJhZ2VTdGF0dXNcIjogXCJBY3RpdmVcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZVN0YXR1c1JlYXNvblwiOiBcIkFjdGl2ZVwiLCBcImFwcGxpY2FudENvdmVyYWdlVGVybURhdGVcIjogXCI5OTk5LTEyLTMxVDAwOjAwOjAwLjAwMFpcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZVN1YlN0YXR1c1wiOiBcIkFjdGl2ZVwiLCBcImNvdmVyYWdlUmVzaWR1YWxWYWx1ZUFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVJlZnVuZEFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVRheFJlZnVuZEFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVRvdGFsUmVmdW5kQW1vdW50XCI6IDAuMCwgXCJjb3ZlcmFnZUlkXCI6IDIsIFwicGxhbkNvdmVyYWdlSW5mb0lkXCI6IDQ4MCwgXCJwbGFuUHJvZHVjdEluZm9JZFwiOiAxMTcsIFwiY292ZXJhZ2VNb250aGx5QmVuZWZpdEFtb3VudFwiOiA1OTYuMCwgXCJhcHBsaWNhbnRKb2JMb3NzRWxpZ2liaWxpdHlGbGFnXCI6IFwiWWVzXCIsIFwiY292ZXJhZ2VQcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWdcIjogXCJOXCJ9LCB7XCJjb3ZlcmFnZVNlcXVlbmNlTnVtYmVyXCI6IDEsIFwiY292ZXJhZ2VBbW91bnRcIjogNTk2LjAsIFwiY292ZXJhZ2VQcmVtaXVtQW1vdW50XCI6IDMxOS4wLCBcImNvdmVyYWdlUHJlbWl1bVRheFwiOiAwLjAsIFwiY292ZXJhZ2VSZXNpZHVhbEFtb3VudFwiOiAwLjAsIFwiY292ZXJhZ2V0UmVzaWR1YWxQcmVtaXVtQW1vdW50XCI6IDAuMCwgXCJjb3ZlcmFnZVJlc2lkdWFsUHJlbWl1bVRheFwiOiAwLjAsIFwiY292ZXJhZ2VFZmZlY3RpdmVEYXRlXCI6IFwiMjAxOS0wMy0wN1QwMDowMDowMC4wMDBaXCIsIFwiY292ZXJhZ2VUZXJtXCI6IDg0LjAsIFwiY292ZXJhZ2VFeHBpcnlEYXRlXCI6IFwiMjAyNi0wMy0wN1QwMDowMDowMC4wMDBaXCIsIFwiY292ZXJhZ2VFbGltaW5hdGlvblBlcmlvZFR5cGVcIjogXCI2ME5SXCIsIFwiY292ZXJhZ2VQcm9jZXNzZWRXaXRoRXJyb3JGbGFnXCI6IFwiTlwiLCBcImNvdmVyYWdlTG9naWNhbERlbGV0ZUZsYWdcIjogXCJOXCIsIFwiY292ZXJhZ2VDb2RlXCI6IFwiSkxcIiwgXCJjb3ZlcmFnZUlkZW50aWZpZXJcIjogXCI0XCIsIFwiYXBwbGljYW50Q292ZXJhZ2VTdGF0dXNcIjogXCJBY3RpdmVcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZVN0YXR1c1JlYXNvblwiOiBcIkFjdGl2ZVwiLCBcImFwcGxpY2FudENvdmVyYWdlVGVybURhdGVcIjogXCI5OTk5LTEyLTMxVDAwOjAwOjAwLjAwMFpcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZVN1YlN0YXR1c1wiOiBcIkFjdGl2ZVwiLCBcImNvdmVyYWdlUmVzaWR1YWxWYWx1ZUFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVJlZnVuZEFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVRheFJlZnVuZEFtb3VudFwiOiAwLjAsIFwicHJlbWl1bVRvdGFsUmVmdW5kQW1vdW50XCI6IDAuMCwgXCJjb3ZlcmFnZUlkXCI6IDQsIFwicGxhbkNvdmVyYWdlSW5mb0lkXCI6IDQ4MSwgXCJwbGFuUHJvZHVjdEluZm9JZFwiOiAxMTcsIFwiY292ZXJhZ2VNb250aGx5QmVuZWZpdEFtb3VudFwiOiA1OTYuMCwgXCJhcHBsaWNhbnRKb2JMb3NzRWxpZ2liaWxpdHlGbGFnXCI6IFwiWWVzXCIsIFwiY292ZXJhZ2VQcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWdcIjogXCJOXCJ9LCB7XCJjb3ZlcmFnZVNlcXVlbmNlTnVtYmVyXCI6IDEsIFwiY292ZXJhZ2VBbW91bnRcIjogMTAwMDAuMCwgXCJjb3ZlcmFnZVByZW1pdW1BbW91bnRcIjogNzk3LjUsIFwiY292ZXJhZ2VQcmVtaXVtVGF4XCI6IDAuMCwgXCJjb3ZlcmFnZVJlc2lkdWFsQW1vdW50XCI6IDAuMCwgXCJjb3ZlcmFnZXRSZXNpZHVhbFByZW1pdW1BbW91bnRcIjogMC4wLCBcImNvdmVyYWdlUmVzaWR1YWxQcmVtaXVtVGF4XCI6IDAuMCwgXCJjb3ZlcmFnZUVmZmVjdGl2ZURhdGVcIjogXCIyMDE5LTAzLTA3VDAwOjAwOjAwLjAwMFpcIiwgXCJjb3ZlcmFnZVRlcm1cIjogODQuMCwgXCJjb3ZlcmFnZUV4cGlyeURhdGVcIjogXCIyMDI2LTAzLTA3VDAwOjAwOjAwLjAwMFpcIiwgXCJjb3ZlcmFnZVByb2Nlc3NlZFdpdGhFcnJvckZsYWdcIjogXCJOXCIsIFwiY292ZXJhZ2VMb2dpY2FsRGVsZXRlRmxhZ1wiOiBcIk5cIiwgXCJjb3ZlcmFnZUNvZGVcIjogXCJMSVwiLCBcImNvdmVyYWdlSWRlbnRpZmllclwiOiBcIjFcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZVN0YXR1c1wiOiBcIkFjdGl2ZVwiLCBcImFwcGxpY2FudENvdmVyYWdlU3RhdHVzUmVhc29uXCI6IFwiQWN0aXZlXCIsIFwiYXBwbGljYW50Q292ZXJhZ2VUZXJtRGF0ZVwiOiBcIjk5OTktMTItMzFUMDA6MDA6MDAuMDAwWlwiLCBcImFwcGxpY2FudENvdmVyYWdlU3ViU3RhdHVzXCI6IFwiQWN0aXZlXCIsIFwiY292ZXJhZ2VSZXNpZHVhbFZhbHVlQW1vdW50XCI6IDAuMCwgXCJwcmVtaXVtUmVmdW5kQW1vdW50XCI6IDAuMCwgXCJwcmVtaXVtVGF4UmVmdW5kQW1vdW50XCI6IDAuMCwgXCJwcmVtaXVtVG90YWxSZWZ1bmRBbW91bnRcIjogMC4wLCBcImNvdmVyYWdlSWRcIjogMSwgXCJwbGFuQ292ZXJhZ2VJbmZvSWRcIjogNDc5LCBcInBsYW5Qcm9kdWN0SW5mb0lkXCI6IDExNywgXCJhcHBsaWNhbnRKb2JMb3NzRWxpZ2liaWxpdHlGbGFnXCI6IFwiWWVzXCIsIFwiY292ZXJhZ2VQcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWdcIjogXCJOXCJ9XSwgXCJhcHBsaWNhbnRQcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWdcIjogXCJOXCJ9XSwgXCJjcmVkaXRvclwiOiB7XCJjcmVkaXRvckJ1c2luZXNzTmFtZVwiOiBcIkJNTyBCYW5rIG9mIE1vbnRyZWFsIGMvbyBJbnN1cmFuY2UgSGlnaHdheVwiLCBcImNyZWRpdG9yQWRkcmVzc0xpbmUxXCI6IFwiMiBSb2JlcnQgU3BlY2sgUGFya3dheSAxNXRoIEZsb29yXCIsIFwiY3JlZGl0b3JDaXR5XCI6IFwiTWlzc2lzc2F1Z2FcIiwgXCJjcmVkaXRvclByb3ZpbmNlXCI6IFwiT05cIiwgXCJjcmVkaXRvclBvc3RhbENvZGVcIjogXCJMNFogMUg4XCIsIFwiY3JlZGl0b3JQaG9uZTFcIjogXCI5OTk5OTk5OTk5XCIsIFwiY3JlZGl0b3JDb3VudHJ5XCI6IFwiQ0FcIiwgXCJjcmVkaXRvckxhbmd1YWdlQ29kZVwiOiBcIkVOXCIsIFwiY3JlZGl0b3JMYXN0VXBkYXRlZERhdGVcIjogXCIyMDIxLTA1LTA3VDAzOjU0OjM4LjAwMFpcIiwgXCJjcmVkaXRvckNsaWVudElkZW50aWZpZXJcIjogMSwgXCJjcmVkaXRvck51bWJlclwiOiBcIjFcIiwgXCJjcmVkaXRvckdyb3VwUG9saWN5SG9sZGVyXCI6IDF9LCBcImdyb3VwUG9saWN5SG9sZGVyXCI6IHtcImdyb3VwUG9saWN5SG9sZGVyQnVzaW5lc3NOYW1lXCI6IFwiUG9ydCBDaXR5IEtpYVwiLCBcImdyb3VwUG9saWN5SG9sZGVyQWRkcmVzc0xpbmUxXCI6IFwiNTUwIFJvdGhlc2F5IEF2ZW51ZSBcIiwgXCJncm91cFBvbGljeUhvbGRlckNpdHlcIjogXCJTYWludCBKb2huXCIsIFwiZ3JvdXBQb2xpY3lIb2xkZXJQcm92aW5jZVwiOiBcIk5CXCIsIFwiZ3JvdXBQb2xpY3lIb2xkZXJQb3N0YWxDb2RlXCI6IFwiRTJKIDJDNFwiLCBcImdyb3VwUG9saWN5SG9sZGVyUGhvbmUxXCI6IFwiNTA2NjM1MTYwMFwiLCBcImdyb3VwUG9saWN5SG9sZGVyQ291bnRyeVwiOiBcIkNBXCIsIFwiZ3JvdXBQb2xpY3lIb2xkZXJMYW5ndWFnZUNvZGVcIjogXCJFTlwiLCBcImdyb3VwUG9saWN5SG9sZGVyTGFzdFVwZGF0ZWREYXRlXCI6IFwiMjAyMS0wNS0wN1QwMzo1NDozOC4wMDBaXCIsIFwiZ3JvdXBQb2xpY3lIb2xkZXJDbGllbnRJZGVudGlmaWVyXCI6IDEsIFwiZ3JvdXBQb2xpY3lIb2xkZXJOdW1iZXJcIjogXCIxXCIsIFwiZ3JvdXBQb2xpY3lIb2xkZXJEZWFsZXJSZW1pdHNUYXhcIjogXCJOb1wifSwgXCJtZXJjaGFudFwiOiB7XCJtZXJjaGFudE51bWJlclwiOiBcIm4vYVwifSwgXCJjZXJ0aWZpY2F0ZVByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZ1wiOiBcIk5cIn19In0\u003d" }
        // this.certificateDetails = JSON.parse(atob(data.value));
        // this.fetchPremiumHistory(event);
        // this.fetchTransactionAuditHistory(event);
      })

  }

  fetchPremiumHistory(event) {
    let premiumHistoryFormvariables = {
      certificateId: event.data.certificateIdentifier
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchPremiumHistory-SP', JSON.stringify(premiumHistoryFormvariables), null).subscribe(
      data => {
        this.premiumHistory = atob(data.value)
      }, error => {
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJwcmVtaXVtTGlzdFNQX3ByZW1pdW0iOlt7InRvdGFsVGF4IjoxNjIuMjUsImJhc2VUcmFuc2FjdGlvblR5cGUiOiJSZWluc3RhdGUiLCJ0b3RhbFByZW1pdW1XaXRoVGF4IjoxOTYzLjk2LCJkaXNhYmlsaXR5UHJlbWl1bVRheCI6MTYyLjI1LCJ0b3RhbFByZW1pdW0iOjE4MDEuNzEsImFwcGxpY2FudE5hbWUiOiJDaHd3d3RpYW4gRGVzYmllbnMiLCJ0cmFuc2FjdGlvbkRhdGUiOiIyMDIxLTA5LTI2VDAwOjAwOjAwLjAwMFoiLCJkaXNhYmlsaXR5UHJlbWl1bSI6MTgwMS43MX0seyJ0b3RhbFRheCI6MTYyLjI1LCJiYXNlVHJhbnNhY3Rpb25UeXBlIjoiTmV3IEJ1c2luZXNzIiwidG90YWxQcmVtaXVtV2l0aFRheCI6MTk2NC45OCwiZGlzYWJpbGl0eVByZW1pdW1UYXgiOjE2Mi4yNSwidG90YWxQcmVtaXVtIjoxODAyLjczLCJhcHBsaWNhbnROYW1lIjoiQ2h3d3d0aWFuIERlc2JpZW5zIiwidHJhbnNhY3Rpb25EYXRlIjoiMjAyMC0wNC0yMVQwMDowMDowMC4wMDBaIiwiZGlzYWJpbGl0eVByZW1pdW0iOjE4MDIuNzN9LHsidG90YWxUYXgiOi0xNTMuODksImJhc2VUcmFuc2FjdGlvblR5cGUiOiJDYW5jZWxsYXRpb24iLCJ0b3RhbFByZW1pdW1XaXRoVGF4IjotMTkwNC4zNSwiZGlzYWJpbGl0eVByZW1pdW1UYXgiOi0xNTMuODksInRvdGFsUHJlbWl1bSI6LTE3NTAuNDYsImFwcGxpY2FudE5hbWUiOiJDaHd3d3RpYW4gRGVzYmllbnMiLCJ0cmFuc2FjdGlvbkRhdGUiOiIyMDE5LTA3LTI1VDAwOjAwOjAwLjAwMFoiLCJkaXNhYmlsaXR5UHJlbWl1bSI6LTE3NTAuNDZ9XX0\u003d" };
        // this.premiumHistory = atob(data.value)
      }
    )
  }
  fetchTransactionAuditHistory(event) {
    debugger;
    let auditHistoryFormvariables = {
      fileHeaderId: event.data.fileHeaderIdentifier,
      certificateNumber: event.data.certificateNumber
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchTransactionAuditHistory', JSON.stringify(auditHistoryFormvariables), null).subscribe(
      data => {
        this.auditHistoryDetails = JSON.parse(atob(data.value));
        this.isShowCertificateDetail = true;
      }, error => {
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJhdWRpdEhpc3RvcnlKc29uIjoie1wiYXVkaXRIaXN0b3J5RGF0YVwiOiB7XCJhcHBsaWNhbnRBdWRpdEhpc3RvcnlcIjogW10sIFwiYXBwbGljYW50QWRkcmVzc0F1ZGl0SGlzdG9yeVwiOiBbXSwgXCJhcHBsaWNhbnRDb3ZlcmFnZUF1ZGl0SGlzdG9yeVwiOiBbe1wiYXVkaXRIaXN0b3J5SWRlbnRpZmllclwiOiBcIjMyMTMxXCIsIFwiZmlsZUhlYWRlcklkZW50aWZpZXJcIjogXCI5MTQ4XCIsIFwiY2VydGlmaWNhdGVOdW1iZXJcIjogXCJDSTAwMDAwMDAwMDc2Mzk3XCIsIFwiYXBwbGljYW50SWRlbnRpZmllclwiOiBcIjgzOTQ5XCIsIFwic2VxdWVuY2VOdW1iZXJcIjogXCIxXCIsIFwiYXBwbGljYW50Q292ZXJhZ2VJZGVudGlmaWVyXCI6IFwiMTQ1NTA0XCIsIFwidHJhbnNhY3Rpb25UeXBlXCI6IFwiQ2FuY2VsbGF0aW9uXCIsIFwiY292ZXJhZ2VJZFwiOiBcIjJcIiwgXCJjb3ZlcmFnZUNvZGVcIjogXCJESVwiLCBcInVwZGF0ZWREYXRhYmFzZUZpZWxkTmFtZVwiOiBcIkFwcGxpY2FudENvdlN0YXR1c1wiLCBcInVwZGF0ZWRVSUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlIFN0YXR1c1wiLCBcIm9sZFZhbHVlXCI6IFwiQWN0aXZlXCIsIFwibmV3VmFsdWVcIjogXCJUZXJtaW5hdGVkXCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMDo1NC4yMzdcIiwgXCJhcHBsaWNhbnROYW1lXCI6IFwiQ2h3d3d0aWFuIERlc2JpZW5zXCJ9LCB7XCJhdWRpdEhpc3RvcnlJZGVudGlmaWVyXCI6IFwiMzIxMzJcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDhcIiwgXCJjZXJ0aWZpY2F0ZU51bWJlclwiOiBcIkNJMDAwMDAwMDAwNzYzOTdcIiwgXCJhcHBsaWNhbnRJZGVudGlmaWVyXCI6IFwiODM5NDlcIiwgXCJzZXF1ZW5jZU51bWJlclwiOiBcIjFcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZUlkZW50aWZpZXJcIjogXCIxNDU1MDRcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJDYW5jZWxsYXRpb25cIiwgXCJjb3ZlcmFnZUlkXCI6IFwiMlwiLCBcImNvdmVyYWdlQ29kZVwiOiBcIkRJXCIsIFwidXBkYXRlZERhdGFiYXNlRmllbGROYW1lXCI6IFwiQXBwbGljYW50Q292VGVybWluYXRpb25EdFwiLCBcInVwZGF0ZWRVSUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlIFRlcm1pbmF0aW9uIERhdGVcIiwgXCJvbGRWYWx1ZVwiOiBcIkRlYyAzMSwgOTk5OVwiLCBcIm5ld1ZhbHVlXCI6IFwiSnVsIDMwLCAyMDIwXCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMDo1NC4yMzdcIiwgXCJhcHBsaWNhbnROYW1lXCI6IFwiQ2h3d3d0aWFuIERlc2JpZW5zXCJ9LCB7XCJhdWRpdEhpc3RvcnlJZGVudGlmaWVyXCI6IFwiMzIxMzNcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDhcIiwgXCJjZXJ0aWZpY2F0ZU51bWJlclwiOiBcIkNJMDAwMDAwMDAwNzYzOTdcIiwgXCJhcHBsaWNhbnRJZGVudGlmaWVyXCI6IFwiODM5NDlcIiwgXCJzZXF1ZW5jZU51bWJlclwiOiBcIjFcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZUlkZW50aWZpZXJcIjogXCIxNDU1MDRcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJDYW5jZWxsYXRpb25cIiwgXCJjb3ZlcmFnZUlkXCI6IFwiMlwiLCBcImNvdmVyYWdlQ29kZVwiOiBcIkRJXCIsIFwidXBkYXRlZERhdGFiYXNlRmllbGROYW1lXCI6IFwiQXBwbGljYW50Q292U3ViU3RhdHVzXCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiQ292ZXJhZ2UgU3ViIFN0YXR1c1wiLCBcIm9sZFZhbHVlXCI6IFwiQWN0aXZlXCIsIFwibmV3VmFsdWVcIjogXCJUZXJtaW5hdGVkXCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMDo1NC4yMzdcIiwgXCJhcHBsaWNhbnROYW1lXCI6IFwiQ2h3d3d0aWFuIERlc2JpZW5zXCJ9LCB7XCJhdWRpdEhpc3RvcnlJZGVudGlmaWVyXCI6IFwiMzIxNjFcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDlcIiwgXCJjZXJ0aWZpY2F0ZU51bWJlclwiOiBcIkNJMDAwMDAwMDAwNzYzOTdcIiwgXCJhcHBsaWNhbnRJZGVudGlmaWVyXCI6IFwiODM5NDlcIiwgXCJzZXF1ZW5jZU51bWJlclwiOiBcIjFcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZUlkZW50aWZpZXJcIjogXCIxNDU1MDRcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJSZWluc3RhdGVtZW50XCIsIFwiY292ZXJhZ2VJZFwiOiBcIjJcIiwgXCJjb3ZlcmFnZUNvZGVcIjogXCJESVwiLCBcInVwZGF0ZWREYXRhYmFzZUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlUHJlbWl1bUFtdFwiLCBcInVwZGF0ZWRVSUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlIFByZW1pdW0gQW1vdW50XCIsIFwib2xkVmFsdWVcIjogXCIxODAyLjczXCIsIFwibmV3VmFsdWVcIjogXCIxODAxLjcxXCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMzo1NC44OFwiLCBcImFwcGxpY2FudE5hbWVcIjogXCJDaHd3d3RpYW4gRGVzYmllbnNcIn0sIHtcImF1ZGl0SGlzdG9yeUlkZW50aWZpZXJcIjogXCIzMjE2MlwiLCBcImZpbGVIZWFkZXJJZGVudGlmaWVyXCI6IFwiOTE0OVwiLCBcImNlcnRpZmljYXRlTnVtYmVyXCI6IFwiQ0kwMDAwMDAwMDA3NjM5N1wiLCBcImFwcGxpY2FudElkZW50aWZpZXJcIjogXCI4Mzk0OVwiLCBcInNlcXVlbmNlTnVtYmVyXCI6IFwiMVwiLCBcImFwcGxpY2FudENvdmVyYWdlSWRlbnRpZmllclwiOiBcIjE0NTUwNFwiLCBcInRyYW5zYWN0aW9uVHlwZVwiOiBcIlJlaW5zdGF0ZW1lbnRcIiwgXCJjb3ZlcmFnZUlkXCI6IFwiMlwiLCBcImNvdmVyYWdlQ29kZVwiOiBcIkRJXCIsIFwidXBkYXRlZERhdGFiYXNlRmllbGROYW1lXCI6IFwiQ292ZXJhZ2VFZmZlY3RpdmVEYXRlXCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiQ292ZXJhZ2UgRWZmZWN0aXZlIERhdGVcIiwgXCJvbGRWYWx1ZVwiOiBcIk1hciAzMCwgMjAyMFwiLCBcIm5ld1ZhbHVlXCI6IFwiSnVsIDMwLCAyMDE5XCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMzo1NC44OFwiLCBcImFwcGxpY2FudE5hbWVcIjogXCJDaHd3d3RpYW4gRGVzYmllbnNcIn0sIHtcImF1ZGl0SGlzdG9yeUlkZW50aWZpZXJcIjogXCIzMjE2M1wiLCBcImZpbGVIZWFkZXJJZGVudGlmaWVyXCI6IFwiOTE0OVwiLCBcImNlcnRpZmljYXRlTnVtYmVyXCI6IFwiQ0kwMDAwMDAwMDA3NjM5N1wiLCBcImFwcGxpY2FudElkZW50aWZpZXJcIjogXCI4Mzk0OVwiLCBcInNlcXVlbmNlTnVtYmVyXCI6IFwiMVwiLCBcImFwcGxpY2FudENvdmVyYWdlSWRlbnRpZmllclwiOiBcIjE0NTUwNFwiLCBcInRyYW5zYWN0aW9uVHlwZVwiOiBcIlJlaW5zdGF0ZW1lbnRcIiwgXCJjb3ZlcmFnZUlkXCI6IFwiMlwiLCBcImNvdmVyYWdlQ29kZVwiOiBcIkRJXCIsIFwidXBkYXRlZERhdGFiYXNlRmllbGROYW1lXCI6IFwiQXBwbGljYW50Q292U3RhdHVzXCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiQ292ZXJhZ2UgU3RhdHVzXCIsIFwib2xkVmFsdWVcIjogXCJUZXJtaW5hdGVkXCIsIFwibmV3VmFsdWVcIjogXCJBY3RpdmVcIiwgXCJ0cmFuc2FjdGlvbkRhdGVcIjogXCIyMDIxLTA0LTI3IDExOjMzOjU0Ljg4XCIsIFwiYXBwbGljYW50TmFtZVwiOiBcIkNod3d3dGlhbiBEZXNiaWVuc1wifSwge1wiYXVkaXRIaXN0b3J5SWRlbnRpZmllclwiOiBcIjMyMTY0XCIsIFwiZmlsZUhlYWRlcklkZW50aWZpZXJcIjogXCI5MTQ5XCIsIFwiY2VydGlmaWNhdGVOdW1iZXJcIjogXCJDSTAwMDAwMDAwMDc2Mzk3XCIsIFwiYXBwbGljYW50SWRlbnRpZmllclwiOiBcIjgzOTQ5XCIsIFwic2VxdWVuY2VOdW1iZXJcIjogXCIxXCIsIFwiYXBwbGljYW50Q292ZXJhZ2VJZGVudGlmaWVyXCI6IFwiMTQ1NTA0XCIsIFwidHJhbnNhY3Rpb25UeXBlXCI6IFwiUmVpbnN0YXRlbWVudFwiLCBcImNvdmVyYWdlSWRcIjogXCIyXCIsIFwiY292ZXJhZ2VDb2RlXCI6IFwiRElcIiwgXCJ1cGRhdGVkRGF0YWJhc2VGaWVsZE5hbWVcIjogXCJBcHBsaWNhbnRDb3ZUZXJtaW5hdGlvbkR0XCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiQ292ZXJhZ2UgVGVybWluYXRpb24gRGF0ZVwiLCBcIm9sZFZhbHVlXCI6IFwiSnVsIDMwLCAyMDIwXCIsIFwibmV3VmFsdWVcIjogXCJEZWMgMzEsIDk5OTlcIiwgXCJ0cmFuc2FjdGlvbkRhdGVcIjogXCIyMDIxLTA0LTI3IDExOjMzOjU0Ljg4XCIsIFwiYXBwbGljYW50TmFtZVwiOiBcIkNod3d3dGlhbiBEZXNiaWVuc1wifSwge1wiYXVkaXRIaXN0b3J5SWRlbnRpZmllclwiOiBcIjMyMTY1XCIsIFwiZmlsZUhlYWRlcklkZW50aWZpZXJcIjogXCI5MTQ5XCIsIFwiY2VydGlmaWNhdGVOdW1iZXJcIjogXCJDSTAwMDAwMDAwMDc2Mzk3XCIsIFwiYXBwbGljYW50SWRlbnRpZmllclwiOiBcIjgzOTQ5XCIsIFwic2VxdWVuY2VOdW1iZXJcIjogXCIxXCIsIFwiYXBwbGljYW50Q292ZXJhZ2VJZGVudGlmaWVyXCI6IFwiMTQ1NTA0XCIsIFwidHJhbnNhY3Rpb25UeXBlXCI6IFwiUmVpbnN0YXRlbWVudFwiLCBcImNvdmVyYWdlSWRcIjogXCIyXCIsIFwiY292ZXJhZ2VDb2RlXCI6IFwiRElcIiwgXCJ1cGRhdGVkRGF0YWJhc2VGaWVsZE5hbWVcIjogXCJBcHBsaWNhbnRDb3ZTdWJTdGF0dXNcIiwgXCJ1cGRhdGVkVUlGaWVsZE5hbWVcIjogXCJDb3ZlcmFnZSBTdWIgU3RhdHVzXCIsIFwib2xkVmFsdWVcIjogXCJUZXJtaW5hdGVkXCIsIFwibmV3VmFsdWVcIjogXCJSZS1JbnN0YXRlZFwiLCBcInRyYW5zYWN0aW9uRGF0ZVwiOiBcIjIwMjEtMDQtMjcgMTE6MzM6NTQuODhcIiwgXCJhcHBsaWNhbnROYW1lXCI6IFwiQ2h3d3d0aWFuIERlc2JpZW5zXCJ9LCB7XCJhdWRpdEhpc3RvcnlJZGVudGlmaWVyXCI6IFwiMzIxNjZcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDlcIiwgXCJjZXJ0aWZpY2F0ZU51bWJlclwiOiBcIkNJMDAwMDAwMDAwNzYzOTdcIiwgXCJhcHBsaWNhbnRJZGVudGlmaWVyXCI6IFwiODM5NDlcIiwgXCJzZXF1ZW5jZU51bWJlclwiOiBcIjFcIiwgXCJhcHBsaWNhbnRDb3ZlcmFnZUlkZW50aWZpZXJcIjogXCIxNDU1MDRcIiwgXCJ0cmFuc2FjdGlvblR5cGVcIjogXCJSZWluc3RhdGVtZW50XCIsIFwiY292ZXJhZ2VJZFwiOiBcIjJcIiwgXCJjb3ZlcmFnZUNvZGVcIjogXCJESVwiLCBcInVwZGF0ZWREYXRhYmFzZUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlUmVzaWR1YWxWYWx1ZUFtdFwiLCBcInVwZGF0ZWRVSUZpZWxkTmFtZVwiOiBcIkNvdmVyYWdlIFJlc2lkdWFsIFZhbHVlIEFtb3VudFwiLCBcIm9sZFZhbHVlXCI6IFwiMTAwLjAwMFwiLCBcIm5ld1ZhbHVlXCI6IFwiMC4wMDBcIiwgXCJ0cmFuc2FjdGlvbkRhdGVcIjogXCIyMDIxLTA0LTI3IDExOjMzOjU0Ljg4XCIsIFwiYXBwbGljYW50TmFtZVwiOiBcIkNod3d3dGlhbiBEZXNiaWVuc1wifV0sIFwiYXBwbGljYW50Q3JlZGl0b3JBdWRpdEhpc3RvcnlcIjogW10sIFwiYXBwbGljYW50TG9hbkF1ZGl0SGlzdG9yeVwiOiBbe1wiYXVkaXRIaXN0b3J5SWRlbnRpZmllclwiOiBcIjczMTNcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDlcIiwgXCJjZXJ0aWZpY2F0ZUlkZW50aWZpZXJcIjogXCI3NzcxM1wiLCBcInRyYW5zYWN0aW9uVHlwZVwiOiBcIlJlaW5zdGF0ZW1lbnRcIiwgXCJ1cGRhdGVkRGF0YWJhc2VGaWVsZE5hbWVcIjogXCJMb2FuQW10V2l0aG91dEluc3VyYW5jZUxPQ0xpbWl0XCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiTG9hbiBBbW91bnQgV2l0aG91dCBJbnN1cmFuY2VcIiwgXCJvbGRWYWx1ZVwiOiBcIjI3NDc5LjcxMFwiLCBcIm5ld1ZhbHVlXCI6IFwiMjk0NDQuNjkwXCIsIFwidHJhbnNhY3Rpb25EYXRlXCI6IFwiMjAyMS0wNC0yNyAxMTozMzo1NC45OFwifSwge1wiYXVkaXRIaXN0b3J5SWRlbnRpZmllclwiOiBcIjczMTRcIiwgXCJmaWxlSGVhZGVySWRlbnRpZmllclwiOiBcIjkxNDlcIiwgXCJjZXJ0aWZpY2F0ZUlkZW50aWZpZXJcIjogXCI3NzcxM1wiLCBcInRyYW5zYWN0aW9uVHlwZVwiOiBcIlJlaW5zdGF0ZW1lbnRcIiwgXCJ1cGRhdGVkRGF0YWJhc2VGaWVsZE5hbWVcIjogXCJMb2FuRWZmZWN0aXZlRHRcIiwgXCJ1cGRhdGVkVUlGaWVsZE5hbWVcIjogXCJMb2FuIEVmZmVjdGl2ZSBEYXRlXCIsIFwib2xkVmFsdWVcIjogXCJNYXIgMzAsIDIwMjBcIiwgXCJuZXdWYWx1ZVwiOiBcIkRlYyAzMSwgMjAxN1wiLCBcInRyYW5zYWN0aW9uRGF0ZVwiOiBcIjIwMjEtMDQtMjcgMTE6MzM6NTQuOTgzXCJ9LCB7XCJhdWRpdEhpc3RvcnlJZGVudGlmaWVyXCI6IFwiNzMxNVwiLCBcImZpbGVIZWFkZXJJZGVudGlmaWVyXCI6IFwiOTE0OVwiLCBcImNlcnRpZmljYXRlSWRlbnRpZmllclwiOiBcIjc3NzEzXCIsIFwidHJhbnNhY3Rpb25UeXBlXCI6IFwiUmVpbnN0YXRlbWVudFwiLCBcInVwZGF0ZWREYXRhYmFzZUZpZWxkTmFtZVwiOiBcIkxvYW5SZXNpZHVhbFZhbHVlQW10XCIsIFwidXBkYXRlZFVJRmllbGROYW1lXCI6IFwiTG9hbiBCYWxsb29uIEFtb3VudFwiLCBcIm9sZFZhbHVlXCI6IFwiMTAwLjAwMFwiLCBcIm5ld1ZhbHVlXCI6IFwiMC4wMDBcIiwgXCJ0cmFuc2FjdGlvbkRhdGVcIjogXCIyMDIxLTA0LTI3IDExOjMzOjU0Ljk4M1wifV0sIFwiYXBwbGljYW50R3JwUGxjeUhvbGRlckF1ZGl0SGlzdG9yeVwiOiBbXX19In0\u003d" }
        // this.auditHistoryDetails = JSON.parse(atob(data.value));
        // this.isShowCertificateDetail = true;
      })
  }

  @HostListener('scroll', ['$event'])
  onScroll(event) {
    // debugger;
    console.log('scrolled', event.target.scrollTop);
    let tracker = event.target;
    let limit = tracker.scrollHeight - tracker.clientHeight;
    console.log(Math.round(event.target.scrollTop), limit);
    if (Math.round(event.target.scrollTop) === limit) {     
      console.log('end reached');
      this.onScrollDown(this.creditorCertificateList);
    } else if (Math.round(event.target.scrollTop) === limit - 1) {
      console.log("Math.round(event.target.scrollTop)-1", Math.round(event.target.scrollTop) - 1);
      console.log('end reached');
      this.onScrollDown(this.creditorCertificateList);
    }
  }

  onScrollDown(oldGridList) {
    this.isSpinnerShow = true;
    this.isShowCertificateDetail = false;
    let formVariable = {
      fileIdentifier: this.fileIdentifier,
      clientName: this.clientName,
      certificateNumber: this.certificateNumber,
      certificateEffectiveDateMax: this.CEDGreaterThan,
      certificateEffectiveDateMin: this.CEDLessThan,
      internalLocationNumber: this.clientLocationNumber,
      applicantFirstName: this.firstName,
      applicantLastName: this.lastName,
      clientCertificateNumber: this.clientCertificateNo,
      additionalSearchValue: this.additionalSearchValue,
      additionalSearchField: this.additionalSearchField,
      "": this.creditorListCount,
      startRow: this.creditorCertificateList.length,
      numberOfRecordsToFetch: this.numberOfRecordsToFetch
    }
    this.mdMondServiceDS.getFormDataFromMondService('Creditor Self Admin', 'FetchCertificateList', JSON.stringify(formVariable), null).subscribe(
      data => {
        this.creditorCertificateList = [];

        for (var j = 0; j < oldGridList.length; j++) {
          this.creditorCertificateList.push(oldGridList[j]);
          console.log("after push oldGridList,this.creditorCertificateList", this.creditorCertificateList);
          var list = this.creditorCertificateList;
        }
        let creditorGridData = JSON.parse(atob(data.value)).certificateList_certificateSummary;
        for (var i = 0; i < creditorGridData.length; i++) {
          creditorGridData[i]['No'] = oldGridList.length + i;
          if (creditorGridData[i].logicalDeleteFlag == 'N') {
            creditorGridData[i].logicalDeleteFlag = false;
          } else {
            creditorGridData[i].logicalDeleteFlag = true;
          }

          if (creditorGridData[i].processedWithErrors == 'N') {
            creditorGridData[i].processedWithErrors = false;
          } else {
            creditorGridData[i].processedWithErrors = true;
          }
          if (creditorGridData[i].processedWithWarningFlag == 'N') {
            creditorGridData[i].processedWithWarningFlag = false;
          } else {
            creditorGridData[i].processedWithWarningFlag = true;
          }
        }

        for (var k = 0; k < creditorGridData.length; k++) {
          this.creditorCertificateList.push(creditorGridData[k]);
        }
        this.rowsfound = this.creditorListCount + ' rows found' + '( ' + this.creditorCertificateList.length + ' rows fetched )';
        this.isSpinnerShow = false;
      }, error => {
        this.mdMondServiceDS.MDError(error);
        // let data = { "key": "key", "value": "eyJjZXJ0aWZpY2F0ZUxpc3RfY2VydGlmaWNhdGVTdW1tYXJ5IjpbeyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzEzLCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImFwcGxpY2FudE5hbWUiOiJDaHd3d3RpYW4gRGVzYmllbnMiLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNTk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk3IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiTiIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn0seyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzE0LCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImNvYXBwbGljYW50TmFtZSI6IkJyd0RFUklDIExBUVVJTiIsImFwcGxpY2FudE5hbWUiOiJGUndERVJJQyBQQVFVSU4iLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNjk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk4IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiWSIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn0seyJjZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOjc3NzE0LCJjZXJ0aWZpY2F0ZVN1YlN0YXR1cyI6IlJlLUluc3RhdGVkIiwicHJvY2Vzc2VkV2l0aEVycm9ycyI6Ik4iLCJjZXJ0aWZpY2F0ZVN0YXR1cyI6IkFjdGl2ZSIsInBhcnRuZXJOYW1lIjoiTEdNIiwicHJvY2Vzc2VkV2l0aFdhcm5pbmdGbGFnIjoiTiIsImNvYXBwbGljYW50TmFtZSI6IkJyd0RFUklDIExBUVVJTiIsImFwcGxpY2FudE5hbWUiOiJGUndERVJJQyBQQVFVSU4iLCJjZXJ0aWZpY2F0ZUVmZmVjdGl2ZURhdGUiOiIyMDE3LTEyLTMxVDAwOjAwOjAwLjAwMFoiLCJ1bmlxdWVDZXJ0aWZpY2F0ZUlkZW50aWZpZXIiOiI5MDAyNjk5IiwiY2VydGlmaWNhdGVOdW1iZXIiOiJDSTAwMDAwMDAwMDc2Mzk4IiwiZmlsZUhlYWRlcklkZW50aWZpZXIiOjkxNDcsImxvZ2ljYWxEZWxldGVGbGFnIjoiWSIsInByb2R1Y3RUeXBlIjoiU1AifSx7ImNlcnRpZmljYXRlSWRlbnRpZmllciI6Nzc3MTQsImNlcnRpZmljYXRlU3ViU3RhdHVzIjoiUmUtSW5zdGF0ZWQiLCJwcm9jZXNzZWRXaXRoRXJyb3JzIjoiTiIsImNlcnRpZmljYXRlU3RhdHVzIjoiQWN0aXZlIiwicGFydG5lck5hbWUiOiJMR00iLCJwcm9jZXNzZWRXaXRoV2FybmluZ0ZsYWciOiJOIiwiY29hcHBsaWNhbnROYW1lIjoiQnJ3REVSSUMgTEFRVUlOIiwiYXBwbGljYW50TmFtZSI6IkZSd0RFUklDIFBBUVVJTiIsImNlcnRpZmljYXRlRWZmZWN0aXZlRGF0ZSI6IjIwMTctMTItMzFUMDA6MDA6MDAuMDAwWiIsInVuaXF1ZUNlcnRpZmljYXRlSWRlbnRpZmllciI6IjkwMDI2OTkiLCJjZXJ0aWZpY2F0ZU51bWJlciI6IkNJMDAwMDAwMDAwNzYzOTgiLCJmaWxlSGVhZGVySWRlbnRpZmllciI6OTE0NywibG9naWNhbERlbGV0ZUZsYWciOiJZIiwicHJvZHVjdFR5cGUiOiJTUCJ9LHsiY2VydGlmaWNhdGVJZGVudGlmaWVyIjo3NzcxNCwiY2VydGlmaWNhdGVTdWJTdGF0dXMiOiJSZS1JbnN0YXRlZCIsInByb2Nlc3NlZFdpdGhFcnJvcnMiOiJOIiwiY2VydGlmaWNhdGVTdGF0dXMiOiJBY3RpdmUiLCJwYXJ0bmVyTmFtZSI6IkxHTSIsInByb2Nlc3NlZFdpdGhXYXJuaW5nRmxhZyI6Ik4iLCJjb2FwcGxpY2FudE5hbWUiOiJCcndERVJJQyBMQVFVSU4iLCJhcHBsaWNhbnROYW1lIjoiRlJ3REVSSUMgUEFRVUlOIiwiY2VydGlmaWNhdGVFZmZlY3RpdmVEYXRlIjoiMjAxNy0xMi0zMVQwMDowMDowMC4wMDBaIiwidW5pcXVlQ2VydGlmaWNhdGVJZGVudGlmaWVyIjoiOTAwMjY5OSIsImNlcnRpZmljYXRlTnVtYmVyIjoiQ0kwMDAwMDAwMDA3NjM5OCIsImZpbGVIZWFkZXJJZGVudGlmaWVyIjo5MTQ3LCJsb2dpY2FsRGVsZXRlRmxhZyI6IlkiLCJwcm9kdWN0VHlwZSI6IlNQIn1dfQ==" };   
      });
  }

}